### ISSUE TITLE
Occasional error spam in console

### ISSUE THREAD

**Issue by Owehttamy** [frikinjay/let-me-despawn#4]
Seems to occur around every 10-30 minutes.

This server is running Paper version git-Paper-381 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 42fecd0)
You are running the latest version
Previous version: git-Paper-376 (MC: 1.19.3)

Plugins (20): Chunky, CoreProtect, DiscordSRV, GPFlags, Graves, GriefPrevention, GSit, InteractiveChat, InteractiveChatDiscordSrvAddon, ItemSwapperPlugin, LetMeDespawn, LuckPerms, OpenInv, Orebfuscator, PlaceholderAPI, ProtocolLib, Skript, Vault, voicechat, WorldEdit

```- [Sat 18:32:52 ERROR EntityLookup] Cannot update chunk status for entity EntityItem['Golden Boots'/376396, uuid='8a45af69-0950-4dde-bda0-70f8fbfe630a', l='ServerLevel[world]', x=-2124.58, y=110.45, z=118.41, cpos=[-133, 7], tl=0, v=false] since entity chunk (-133,7) is receiving update
java.lang.Throwable
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:241)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:388)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addNewEntity(EntityLookup.java:326)
    at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1520)
    at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1423)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:700)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:689)
    at lmd-1.19.2-1.0-bukkit-paper.jar//com.frikinjay.lmd.handlers.DespawnHandler.onMobDespawn_High(DespawnHandler.java:67)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
    at org.bukkit.event.Event.callEvent(Event.java:45)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2651)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2498)
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:279)
    at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194)
    at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304)
    at io.papermc.paper.chunk.system.scheduling.New
- [Sat 18:32:52 ERROR EntityLookup] Cannot update chunk status for entity EntityItem['Golden Leggings'/376397, uuid='0e4e0432-40f7-417a-a638-a40660a05fe3', l='ServerLevel[world]', x=-2124.58, y=110.45, z=118.41, cpos=[-133, 7], tl=0, v=false] since entity chunk (-133,7) is receiving update
java.lang.Throwable
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:241)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:388)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addNewEntity(EntityLookup.java:326)
    at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1520)
    at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1423)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:700)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:689)
    at lmd-1.19.2-1.0-bukkit-paper.jar//com.frikinjay.lmd.handlers.DespawnHandler.onMobDespawn_High(DespawnHandler.java:67)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
    at org.bukkit.event.Event.callEvent(Event.java:45)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2651)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2498)
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:279)
    at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194)
    at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304)
    at io.papermc.paper.chunk.system.scheduling.
- [Sat 18:32:52 ERROR EntityLookup] Cannot update chunk status for entity EntityItem['Golden Chestplate'/376398, uuid='1fa25e06-82aa-431b-92f0-c624b0610cc3', l='ServerLevel[world]', x=-2124.58, y=110.45, z=118.41, cpos=[-133, 7], tl=0, v=false] since entity chunk (-133,7) is receiving update
java.lang.Throwable
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:241)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:388)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addNewEntity(EntityLookup.java:326)
    at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1520)
    at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1423)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:700)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:689)
    at lmd-1.19.2-1.0-bukkit-paper.jar//com.frikinjay.lmd.handlers.DespawnHandler.onMobDespawn_High(DespawnHandler.java:67)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
    at org.bukkit.event.Event.callEvent(Event.java:45)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2651)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2498)
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:279)
    at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194)
    at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304)
    at io.papermc.paper.chunk.system.schedulin
- [Sat 18:32:52 ERROR EntityLookup] Cannot update chunk status for entity EntityItem['Golden Helmet'/376399, uuid='109c8eef-abee-4cfe-9316-7a0a22fbdd85', l='ServerLevel[world]', x=-2124.58, y=110.45, z=118.41, cpos=[-133, 7], tl=0, v=false] since entity chunk (-133,7) is receiving update
java.lang.Throwable
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:241)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:388)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addNewEntity(EntityLookup.java:326)
    at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1520)
    at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1423)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:700)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:689)
    at lmd-1.19.2-1.0-bukkit-paper.jar//com.frikinjay.lmd.handlers.DespawnHandler.onMobDespawn_High(DespawnHandler.java:67)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
    at org.bukkit.event.Event.callEvent(Event.java:45)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2651)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2498)
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:279)
    at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194)
    at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304)
    at io.papermc.paper.chunk.system.scheduling.Ne
- [Sat 18:32:52 ERROR EntityLookup] Cannot update chunk status for entity EntityItem['Golden Chestplate'/376400, uuid='00048c5a-5f4e-469b-964f-5b97524d7caf', l='ServerLevel[world]', x=-2124.58, y=110.45, z=118.41, cpos=[-133, 7], tl=0, v=false] since entity chunk (-133,7) is receiving update
java.lang.Throwable
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:241)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:388)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addNewEntity(EntityLookup.java:326)
    at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1520)
    at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1423)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:700)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:689)
    at lmd-1.19.2-1.0-bukkit-paper.jar//com.frikinjay.lmd.handlers.DespawnHandler.onMobDespawn_High(DespawnHandler.java:72)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
    at org.bukkit.event.Event.callEvent(Event.java:45)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2651)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2498)
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:279)
    at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194)
    at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304)
    at io.papermc.paper.chunk.system.schedulin
  [Sat 18:32:53 INFO  Server] [Not Secure] <8Blue_Tooth8> YES
  [Sat 18:32:54 INFO  Server] [Not Secure] <8Blue_Tooth8> BOW TIME
 
- [Sat 18:33:09 ERROR EntityLookup] Cannot update chunk status for entity EntityItem['Leather Pants'/377000, uuid='bc8baf5a-4ecc-4d5e-96fb-a54358a6caf9', l='ServerLevel[world]', x=-1967.51, y=87.45, z=-144.96, cpos=[-123, -10], tl=0, v=false] since entity chunk (-123,-10) is receiving update
java.lang.Throwable
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:241)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:388)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addNewEntity(EntityLookup.java:326)
    at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1520)
    at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1423)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:700)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:689)
    at lmd-1.19.2-1.0-bukkit-paper.jar//com.frikinjay.lmd.handlers.DespawnHandler.onMobDespawn_High(DespawnHandler.java:67)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
    at org.bukkit.event.Event.callEvent(Event.java:45)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2651)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2498)
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:279)
    at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194)
    at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304)
    at io.papermc.paper.chunk.system.schedulin
- [Sat 18:33:09 ERROR EntityLookup] Cannot update chunk status for entity EntityItem['Leather Pants'/377001, uuid='fdf2b238-e917-467a-91c2-05b205392d6f', l='ServerLevel[world]', x=-1967.51, y=87.45, z=-144.96, cpos=[-123, -10], tl=0, v=false] since entity chunk (-123,-10) is receiving update
java.lang.Throwable
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:241)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:388)
    at io.papermc.paper.chunk.system.entity.EntityLookup.addNewEntity(EntityLookup.java:326)
    at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1520)
    at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1423)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:700)
    at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.dropItem(CraftWorld.java:689)
    at lmd-1.19.2-1.0-bukkit-paper.jar//com.frikinjay.lmd.handlers.DespawnHandler.onMobDespawn_High(DespawnHandler.java:72)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
    at org.bukkit.event.Event.callEvent(Event.java:45)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2651)
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2498)
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:279)
    at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194)
    at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304)
    at io.papermc.paper.chunk.system.schedulin
```

**Comment by ninjakitty844** [comment]
I also get this, unsure if it's causing additional problems or not atm.

**Comment by Apocalypsing** [comment]
I am also running into this same issue under Paper 1.20.1. Server details posted below. I have disabled the plugin for now as the spam is too regular in my case and makes reading the server console difficult. Pretty much all of the stack traces I've seen reference entities in the Nether, like piglins holding crossbows.

```ver
[10:04:53 INFO]: Checking version, please wait...
[10:04:54 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-194 (MC: 1.20.1)
pl
[10:04:55 INFO]: Server Plugins (65):
[10:04:55 INFO]: Paper Plugins:
[10:04:55 INFO]:  - LogFilter, TreasureMapsPlus
[10:04:55 INFO]: Bukkit Plugins:
[10:04:55 INFO]:  - *AlwaysOnline, AngelChest, Bolt, BuildNotifier-Paper, ChatPings, ChatSentinel, ChestSort, Chunky, ChunkyBorder, CleanPing
[10:04:55 INFO]:  Coordinates, CoreProtect, CraftableBundle, *CraftableHorseEquipment, CytologicHorses, DoubleShulkerShells, eBackup, EntityDetection, Essentials, EssentialsDiscord
[10:04:55 INFO]:  EssentialsProtect, EssentialsSpawn, FancyCropTrample, FarmControl, FastLeafDecay, floodgate, FreedomChat, Geyser-Spigot, GreenChunk, GSit
[10:04:55 INFO]:  Hibernate, HiveChecker, InventoryRollbackPlus, Lasso, LetMeDespawn, LiteBans, LPC, LuckPerms, Maintenance, MiniBlocks
[10:04:55 INFO]:  MiniMOTD, MobBundle, *ModReq, OldCombatMechanics, OpenInv, PlaceholderAPI, PremiumVanish, ProtocolLib, PvPManager, rbzNightVision
[10:04:55 INFO]:  ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SilkSpawners, Skript, spark, SwimmingHorses, TAB, TimePauser, UnbreakableLeashes, Vault
[10:04:55 INFO]:  ViaVersion, VirtualBooks, XCatch
ver LetMeDespawn
[10:05:21 INFO]: LetMeDespawn version 1.19.2-1.0-bukkit-paper
[10:05:21 INFO]: Seeks to improve performance by changing mob despawn rules.
[10:05:21 INFO]: Website: frikinjay.com
[10:05:21 INFO]: Author: frikinjay```

**Comment by frikinjay** [comment]
I'll look into this but current motivation to work on the plugin is low because of how strange the plugin ecosystem is

**Comment by TylorTurner** [comment]
I am getting this issue as well. I use 1.19.4
I was curious as to how important this plugin is, did MC not fix this issue or PaperMC? I can't find anything so far explaining to much about the persistent mob issue. Would you mind explaining what issue it solves in 1.19.4 or any version? I was told on a discord this issue was solved a few updates ago but your plugin is still updated to some newer versions.

**Comment by DereC4** [comment]
Solution found was to manually respawn each existing persistent mob that had equipped items, which seems to stop the duplication chunk error. We did this on a Paper 1.21.4 server (derex smp).
