### ISSUE TITLE
Unknown crash occurred when start game

### ISSUE THREAD

**Issue by NeoStarWonV** [frikinjay/let-me-despawn#42]
[1210��2024 17:58:06.424] [pool-5-thread-1/FATAL] [mixin/]: Mixin apply for mod letmedespawn failed letmedespawn.mixins.json:MobMixin from mod letmedespawn -> net.minecraft.world.entity.Mob: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded NullPointerException whilst transforming the mixin class: [MAIN Applicator Phase -> letmedespawn.mixins.json:MobMixin from mod letmedespawn -> Apply Methods -> (Lnet/minecraft/world/entity/Mob;)V:redirect$kfn000$letmedespawn$yeetusCheckus -> Transform Instructions -> GETSTATIC com/frikinjay/almanac/Almanac::pickedItems:Ljava/lang/Boolean;]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [MAIN Applicator Phase -> letmedespawn.mixins.json:MobMixin from mod letmedespawn -> Apply Methods -> (Lnet/minecraft/world/entity/Mob;)V:redirect$kfn000$letmedespawn$yeetusCheckus -> Transform Instructions -> GETSTATIC com/frikinjay/almanac/Almanac::pickedItems:Ljava/lang/Boolean;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:510) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:535) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:521) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.jellysquid.mods.lithium.common.ai.pathing.BlockClassChecker.<clinit>(BlockClassChecker.java:17) ~[%5B��%5D%20radium-mc1.20.1-0.12.4+git.26c9d8e.jar%23805!/:?]
	at net.minecraft.world.level.block.Block.handler$bfj000$radium$postConstruct(Block.java:1639) ~[client-1.20.1-20230612.114412-srg.jar%231212!/:?]
	at net.minecraft.world.level.block.Block.<init>(Block.java:181) ~[client-1.20.1-20230612.114412-srg.jar%231212!/:?]
	at net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:12) ~[client-1.20.1-20230612.114412-srg.jar%231212!/:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:45) ~[client-1.20.1-20230612.114412-srg.jar%231212!/:?]
	at net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:301) ~[client-1.20.1-20230612.114412-srg.jar%231212!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46) ~[client-1.20.1-20230612.114412-srg.jar%231212!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:151) ~[client-1.20.1-20230612.114412-srg.jar%231212!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.isMixin()" because "fieldOwner" is null
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformFieldRef(MixinTargetContext.java:631) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:488) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 33 more

**Comment by NeoStarWonV** [comment]
version1.20.1 and the latest one for letmedespawn

**Comment by frikinjay** [comment]
Can I get the crash report?

**Comment by Nastared** [comment]
i have the same issue

https://pastebin.com/CDab4ADE

here the log
at the end it says
[14Oct2024 15:26:23.277] [pool-4-thread-1/WARN] [mixin/]: Error loading class: com/frikinjay/almanac/Almanac (java.lang.ClassNotFoundException: com.frikinjay.almanac.Almanac)

**Comment by frikinjay** [comment]
@Nastared its not the same issue, refer to #41

**Comment by NeoStarWonV** [comment]
I forgot install the required mod，The problem has been solved
